### ISSUE TITLE
I would like to start populating the database with real data

### ISSUE THREAD

**Issue by devingray** [Say-Their-Name/api#1]
I have created a doc here

https://docs.google.com/spreadsheets/d/1CC6lC5skNBLajX_1Gqc_TTPGcBmip9Otg3x6ggyVahg/edit?usp=sharing

The goal of this document is to collect data that will be populated into the database to serve as a starting point for our API so that we can stop using fake data.

What we are looking for:

```
NAME 
LOCATION
AGE
DATE OF BIRTH
DATE OF THE INCIDENT
NUMBER OF CHILDREN
BIOGRAPHY
CONTEXT
```

**Comment by muya** [comment]
@devingray Have we thought about how the data from this document will be transformed into data that's consumable from the API?

**Comment by devingray** [comment]
@muya Sorry I only see this now. I have already imported the data :)
